### ISSUE TITLE
apt dependency is quite outdated

### ISSUE THREAD

**Issue by webframp** [acornies/dotnetcore-cookbook#10]
Is there a reason the apt dependency is pinned to such an old version of the apt cookbook?

latest release would be: `cookbook 'apt', '~> 5.0.0'`

https://supermarket.chef.io/cookbooks/apt

**Comment by acornies** [comment]
No particular reason other than I'm used to that version of apt cookbook. I will update with next release.

**Comment by acornies** [comment]
Apt decency is now unpinned and can be managed by the consumer in their a role cookbook or environment policy.
