### ISSUE TITLE
vcredist2015 package installation fails on subsequent runs

### ISSUE THREAD

**Issue by sethuprem** [acornies/dotnetcore-cookbook#11]
First time installation goes through fine and  subsequent installations fails with error code 1638.
Could the script be adjusted to skip it if its already installed ? I  would like this to be part of a run list . 
Newbie to chef, if there is a way to avoid it, let me know

**Comment by acornies** [comment]
Just merged #13 will release new patch version soon.

**Comment by acornies** [comment]
v1.1.3 should resolve this issue.
