### ISSUE TITLE
AWS Opsworks Windows

### ISSUE THREAD

**Issue by HaroonSaid** [acornies/dotnetcore-cookbook#12]
Looks like the Windows version has problems with some of the dependencies with Chef 12.2 (current version in AWS Opswork).   

Do you have any workarounds?

**Comment by acornies** [comment]
Do you have an error message or stacktrace that I can work with?

**Comment by acornies** [comment]
Please try again with new version v1.1.3 as there was a fix for Windows installer merged in.
