### ISSUE TITLE
Cookbook maintenance

### ISSUE THREAD

**Issue by kamaradclimber** [acornies/dotnetcore-cookbook#18]
Hello,

I've read in the description of the repo this cookbook is not maintained.
If you need help to maintain it (or if you want to transfer ownership), we (criteo) can volunteer to help.

**Comment by acornies** [comment]
Hi @kamaradclimber, sure! I welcome any help on this repo as it's not my primary focus these days. If you can send me a list of people, I'll add them to this repo as contributors.

**Comment by kamaradclimber** [comment]
If you could add @komuta and myself, that would be great

**Comment by acornies** [comment]
Done.
