### ISSUE TITLE
Relationship to .NET Core Server Hosting bundle

### ISSUE THREAD

**Issue by webframp** [acornies/dotnetcore-cookbook#3]
I noticed you use a different installer than the one linked for download here:

https://docs.asp.net/en/latest/publishing/iis.html#install-the-net-core-windows-server-hosting-bundle

Just curious how you see the relationship between this bundle and the one you're using to install. Are they complementary?

**Comment by acornies** [comment]
Apologies for the lateness (for some reason I wasn't watching this repo) wrote this cookbook when dot.net core first came out and it was the official package at the time. I'll be refreshing this cookbook soon with a much needed update.

**Comment by webframp** [comment]
No problem, I'll watch for the updates. Thanks!

**Comment by acornies** [comment]
I've actually updated the windows installer to utilize this hosting bundle, as it is now available to me and it makes sense in the Windows platform with IIS and such. Here's a PR that is ready to be merged: https://github.com/acornies/dotnetcore-cookbook/pull/8

**Comment by webframp** [comment]
Excellent, nice to see the update!
